/**
 * Builds public/assets/icons.svg — an SVG sprite of the UI icons, generated
 * from the Lucide set via Iconify.
 *
 * Why a build-time sprite rather than Iconify's runtime web component:
 *   - the app is offline-first, and the runtime component fetches icon data
 *     from api.iconify.design on demand, which fails with no network
 *   - our CSP is script-src 'self' / connect-src 'self', with no external hosts
 *
 * The sprite is precached by the service worker, so icons work offline like
 * everything else. Icons inherit text colour via `fill="currentColor"` /
 * `stroke="currentColor"`, so they follow the light/dark theme automatically.
 *
 * Run with `npm run build:icons`. This is NOT part of postinstall: the icon set
 * is a devDependency, so a production install (which omits dev dependencies)
 * could not run it. The generated sprite is committed instead — it only changes
 * when the ICONS map below does.
 *
 * To add an icon: pick a name from https://icones.js.org/collection/lucide,
 * add it to ICONS below, re-run `npm run build:icons`, and commit the result.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const outFile = path.join(projectRoot, 'public', 'assets', 'icons.svg');

// Sprite id -> Lucide icon name. Ids are what markup references, e.g.
// <svg class="icon"><use href="/assets/icons.svg#icon-close"></use></svg>
const ICONS = {
    'icon-close': 'x',
    'icon-settings': 'settings',
    'icon-undo': 'undo-2',
    'icon-redo': 'redo-2',
    'icon-theme-dark': 'moon',
    'icon-theme-light': 'sun',
    'icon-star': 'star',
    'icon-status': 'circle',
    'icon-copy': 'clipboard-copy',
    'icon-share': 'share-2',
    'icon-csv': 'file-spreadsheet',
    'icon-export': 'save',
    'icon-print': 'printer',
    'icon-save-game': 'save',
    'icon-sync-syncing': 'refresh-cw',
    'icon-sync-synced': 'check',
    'icon-sync-error': 'triangle-alert',
    'icon-sync-offline': 'cloud',
    'icon-user': 'user',
    'icon-share-menu': 'upload',
    'icon-export-menu': 'folder',
    'icon-chevron-down': 'chevron-down'
};

const { icons, width: setWidth, height: setHeight } = require('@iconify-json/lucide/icons.json');

const symbols = [];
const missing = [];

for (const [id, name] of Object.entries(ICONS)) {
    const icon = icons[name];
    if (!icon) {
        missing.push(name);
        continue;
    }

    const width = icon.width || setWidth || 24;
    const height = icon.height || setHeight || 24;

    symbols.push(
        `  <symbol id="${id}" viewBox="0 0 ${width} ${height}">${icon.body}</symbol>`
    );
}

if (missing.length) {
    console.warn(`⚠  build-icons: not found in the Lucide set: ${missing.join(', ')}`);
}

// fill="none" / stroke="currentColor" match Lucide's stroke-based drawing style.
const sprite = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-icons.js from @iconify-json/lucide. Do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" style="display:none" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
${symbols.join('\n')}
</svg>
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, sprite);

console.log(`build-icons: wrote ${symbols.length} icon(s) to public/assets/icons.svg`);
